# Maintainer: reekta92 mdag.92988@protonmail.com
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=clin-rs-bin
pkgver=0.5.0-2
pkgrel=1
pkgdesc="Encrypted terminal note-taking app"
url="https://github.com/reekta92/clin-rs"
license=("GPL-3.0")
arch=("x86_64")
provides=("clin-rs")
conflicts=("clin-rs")
source=("https://github.com/reekta92/clin-rs/releases/download/v$pkgver/clin-rs-$pkgver-x86_64.tar.gz")
sha256sums=("a806a7177f30cf08535af22bbf768b602532dd8ad37f1a23149f1cebc4d9c5ca")

package() {
    install -Dm755 clin-rs -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
