# Maintainer: reekta92 mdag.92988@protonmail.com
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=clin-rs-bin
pkgver=0.7.0-61
pkgrel=1
pkgdesc="Encrypted terminal note-taking app"
url="https://github.com/reekta92/clin-rs"
license=("GPL-3.0")
arch=("x86_64")
provides=("clin-rs")
conflicts=("clin-rs")
source=("https://github.com/reekta92/clin-rs/releases/download/v$pkgver/clin-rs-$pkgver-x86_64.tar.gz")
sha256sums=("6c2833cb02b5b0b0838e36b5787c37b5819cff4d04f890b6934f9ae76df77abb")

package() {
    install -Dm755 clin -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
