# Maintainer: reekta <reekta@localhost>
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=clin-bin
pkgver=0.2.1-2
pkgrel=1
pkgdesc="Encrypted terminal note-taking app"
url="https://github.com/reekta92/clin-rs"
license=("GPLv3")
arch=("x86_64")
provides=("clin")
conflicts=("clin")
source=("https://github.com/reekta92/clin-rs/releases/download/v$pkgver/clin-$pkgver-x86_64.tar.gz")
sha256sums=("2f265c6bd8cbf96ee6b11b3080d0a8da0187a7fcaa2b515064f47f9455bf4ef3")

package() {
    install -Dm755 clin -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
